language: java

jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2"

script:
  - mvn clean install -B checkstyle:check
  - mvn -B jacoco:report coveralls:report -DrepoToken="${evn.COVERALLS_TOKEN}"