spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:masterdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 2000000
      minimumIdle: 5
      maximumPoolSize: 20
      connection-test-query: SELECT 1

  flyway:
    locations: classpath:/db/migration/{vendor}

#  profiles:
#    active: logkafka